# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/HardLinkTool.UI"
    schedule:
      interval: "daily"
    groups:
      Avalonia:
        patterns: [ "Avalonia*" ]
      ui-dependence:
        patterns: [ "Microsoft.Extensions.DependencyInjection","Xaml.Behaviors*", "StaticViewLocator" ]
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]

  - package-ecosystem: "nuget"
    directory: "/HardLinkTool.ConsoleApp"
    schedule:
      interval: "daily"
    groups:
      console-dependence:
        patterns: [ "System.CommandLine" ]
    ignore:
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      other-dependence:
        patterns: [ "*" ]
    ignore:
      - dependency-name: "Avalonia.*"
      - dependency-name: "Microsoft.Extensions.DependencyInjection"
      - dependency-name: "Xaml.Behaviors.*"
      - dependency-name: "System.CommandLine"
      - dependency-name: "StaticViewLocator"
      - dependency-name: "*"
        update-types: [ "version-update:semver-major" ]
