name: Release

on:
  push:
    tags:
      - "v*"

defaults:
  run:
    working-directory: ./HardLinkTool

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    
    - uses: actions/setup-dotnet@v4
      name: Setup dotnet
      with:
        dotnet-version: '9.0.*'
    
    - name: Install dependencies
      run: dotnet restore

    - name: Build windows x64
      run: dotnet publish -c Release -r win-x64 -f net9.0 --no-restore

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ./bin\Release\net9.0\win-x64\publish\HardLinkTool.exe
          LICENSE
