name: Release

on:
  push:
    tags:
      - "v*"

defaults:
  run:
    working-directory: ./HardLinkTool

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    
    - uses: actions/setup-dotnet@v4
      name: Setup dotnet
      with:
        dotnet-version: '9.0.*'

    - name: Build windows x64
      shell: pwsh
      run: ../scripts/publish.ps1

    - name: Create release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          HardLinkTool/publish/HardLinkTool.exe
          LICENSE
